Add (and use) COND
tarballs-are-good/coalton pull request #13
Opened 2019-12-14 22:12 UTC by notmgsk

2019-12-14 22:13 UTC, notmgsk commented on src/library.lisp
> +           (cl:assert (cl:eql cl:t clause-a) () "COND must have a catch-all T clause.")
`cl:t` or `otherwise`?

2019-12-14 22:14 UTC, notmgsk commented on src/library.lisp
> +           (cl:assert (cl:eql cl:t clause-a) () "COND must have a catch-all T clause.")
or `else`?

2019-12-14 22:58 UTC, stylewarning requested changes

2019-12-14 22:58 UTC, stylewarning commented on src/library.lisp
> +(cl:defmacro coalton::cond ((clause-a then-a) cl:&rest clauses)
```suggestion
(cl:defmacro coalton:cond ((clause-a then-a) cl:&rest clauses)
```

2019-12-14 22:58 UTC, stylewarning commented on src/library.lisp
> +  (cl:if (cl:not (cl:null clauses))
```suggestion
  (cl:if (cl:not (cl:endp clauses))
```

2019-12-14 22:58 UTC, stylewarning commented on src/library.lisp
> +                      (coalton::cond ,@clauses))
```suggestion
                      (coalton:cond ,@clauses))
```

2019-12-14 22:58 UTC, stylewarning commented on src/library.lisp
> +           (cl:assert (cl:eql 'else clause-a) () "COND must have a catch-all T clause.")
```suggestion
           (cl:assert (cl:eq 'coalton:else clause-a) () "COND must have an ELSE clause.")
```

2019-12-14 22:58 UTC, stylewarning commented on src/package.lisp
> +   #:cond
```suggestion
   #:cond
   #:else          ; syntax for COND
```

2019-12-14 22:58 UTC, stylewarning commented on src/library.lisp
> +                           (else      (gcd (half (- v u)) u)))))))
Beautiful!

2019-12-14 23:44 UTC, notmgsk commented
@stylewarning I added a couple more changes that might be controversial. Namely, I removed the `coalton:` prefixes in places where they're not technically required, and I capitalised the symbols `false` and `true`. I can revert those if you think it's better to be clear about where those symbols are coming from.

2019-12-15 01:15 UTC, stylewarning approved these changes

2019-12-15 01:15 UTC, stylewarning commented on src/library.lisp
> -     (coalton:true ,then)
Removal here is OK. I mostly want to keep the prefixes at definitions.

2019-12-15 01:15 UTC, stylewarning commented on src/library.lisp
> +  (cl:if x True False))
good change, I prefer this

2019-12-15 01:16 UTC, merged